# Copyright 2019-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

resources:
  enabled: false

cassandra:
  config:
    cluster_size: 1

config:
  sriov:
    enabled: false
  spgwu:
    devices: "--no-pci --vdev eth_af_packet0,iface=s1u-net --vdev eth_af_packet1,iface=sgi-net"
  plmn:
    name: "COMAC Test Network"
    short_name: "COMAC"
    mcc: "208"
    mnc: "01"
  enb:
    mme:
      address: 127.0.0.1
    networks:
      s1u:
        interface: s1u-enb
  ue:
    # 1 UE is supported for now
    name: ue
    sim:
      msin: "4567891201"
      api_key: "465b5ce8b199b49faa5f0a2ee238a6bc"
      opc: "d4416644f6154936193433dd20a0ace0"
      msisdn: "1122334456"

networks:
  cniPlugin: simpleovs
  ipam: static

# cord-platform values
etcd-operator:
  enabled: false
logging:
  enabled: false
nem-monitoring:
  enabled: true

# comac-platform values
mcord-setup:
  enabled: false
etcd-cluster:
  enabled: false
